# Generated by Django 3.2.3 on 2021-05-22 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20210522_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainbanner',
            old_name='img',
            new_name='eventimg',
        ),
    ]
