# Generated by Django 3.2.3 on 2021-05-24 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20210524_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainbanner',
            old_name='maintimg',
            new_name='mainimg',
        ),
    ]
